#!/usr/bin/env python3
"""Generate and validate the stable ``base_cli`` API reference.

The reference is intentionally derived from the package facade rather than
from every importable module.  This keeps private implementation details out
of the published documentation while making a public-export change fail the
documentation check until the generated page is refreshed.
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "lib" / "python"
REFERENCE = ROOT / "docs" / "api-reference.md"
MARKER = "<!-- generated by scripts/generate_api_reference.py; do not edit -->"
HEADING_PATTERN = re.compile(r"^### `([^`]+)`$", re.MULTILINE)


def _load_package() -> Any:
    sys.path.insert(0, str(PACKAGE_ROOT))
    import base_cli

    return base_cli


def _kind(value: Any) -> str:
    if inspect.ismodule(value):
        return "module"
    if inspect.isclass(value):
        return "class"
    if inspect.isfunction(value) or inspect.ismethod(value):
        return "function"
    if isinstance(value, type):
        return "class"
    return "constant/type"


def _signature(name: str, value: Any) -> str:
    try:
        if inspect.isclass(value) or inspect.isfunction(value) or inspect.ismethod(value):
            signature = str(inspect.signature(value))
            # Default callback reprs contain process-specific memory addresses.
            signature = re.sub(r" at 0x[0-9a-fA-F]+", "", signature)
            return f"`{name}{signature}`"
    except (TypeError, ValueError):
        pass
    return "(value is not callable)"


def _description(value: Any) -> str:
    doc = inspect.getdoc(value)
    if not doc:
        return "Public facade symbol; see the linked contract and source annotations for details."
    first_paragraph = doc.split("\n\n", 1)[0].replace("\n", " ").strip()
    return first_paragraph


def _example(name: str, value: Any) -> str:
    kind = _kind(value)
    if kind == "module":
        return f"```python\nimport base_cli\n\nbase_cli.{name}\n```"
    if kind in {"function", "class"}:
        return f"```python\nimport base_cli\n\n# See the callable signature above and pass consumer-owned values.\nbase_cli.{name}(...)\n```"
    return f"```python\nimport base_cli\n\nvalue = base_cli.{name}\n```"


def render(base_cli: Any) -> str:
    sections: dict[str, list[str]] = {"class": [], "function": [], "module": [], "constant/type": []}
    for name in base_cli.__all__:
        value = getattr(base_cli, name)
        kind = _kind(value)
        sections[kind].append(
            "\n".join(
                (
                    f"### `{name}`",
                    f"**Kind:** {kind}  ",
                    f"**Signature:** {_signature(name, value)}",
                    "",
                    f"**Behavior:** {_description(value)}",
                    "",
                    "**Errors and compatibility:** Follow the contract documentation linked in the description. "
                    "Callers should handle the documented exception types and pin a compatible minor release.",
                    "",
                    "**Example:**",
                    _example(name, value),
                    "",
                )
            )
        )

    lines = [
        "# Public API reference",
        "",
        "This page is generated from `base_cli.__all__`. It is the complete stable",
        "facade: private modules and names are deliberately excluded. Each entry",
        "includes the runtime signature when Python can inspect one, the public",
        "docstring summary, compatibility guidance, and a minimal usage shape.",
        "For behavior that is shared by several symbols, follow the linked",
        "versioned contracts and the source annotations.",
        "",
        "!!! note",
        "    Regenerate this page after changing a public export:",
        "    `python scripts/generate_api_reference.py`. CI runs the same command",
        "    in check mode and fails when the committed page is stale.",
        "",
        f"{MARKER}",
        "",
        f"The facade currently documents **{len(base_cli.__all__)}** public symbols.",
        "",
    ]
    for title, kind in (
        ("Classes and protocols", "class"),
        ("Functions", "function"),
        ("Modules", "module"),
        ("Constants and typing helpers", "constant/type"),
    ):
        lines.extend([f"## {title}", "", *sections[kind]])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    check = "--check" in sys.argv[1:]
    base_cli = _load_package()
    rendered = render(base_cli)
    if check:
        current = REFERENCE.read_text(encoding="utf-8") if REFERENCE.exists() else ""
        if current != rendered:
            print(f"{REFERENCE.relative_to(ROOT)} is stale; run scripts/generate_api_reference.py", file=sys.stderr)
            raise SystemExit(1)
        documented = set(HEADING_PATTERN.findall(current))
        exported = set(base_cli.__all__)
        if documented != exported:
            print("generated API headings do not match base_cli.__all__", file=sys.stderr)
            raise SystemExit(1)
        print(f"Validated {len(exported)} public API symbols.")
        return
    REFERENCE.write_text(rendered, encoding="utf-8")
    print(f"Generated {REFERENCE.relative_to(ROOT)} for {len(base_cli.__all__)} public symbols.")


if __name__ == "__main__":
    main()
