"""Optional Typer integration for the base-cli lifecycle.

Typer is deliberately not imported when :mod:`base_cli` is imported.  The
adapter materializes Typer's own Click command tree and delegates attachment
to the same Click boundary used by :func:`base_cli.attach`.  This keeps
Typer's command discovery, parameter conversion, dependency injection, help,
completion, and exception handling intact while adding the base-cli runtime
lifecycle.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from typing import TYPE_CHECKING, Any

from ._click_compat import dialect_for_typer, mark_command_dialect
from .app import App, attach
from .context import Context

if TYPE_CHECKING:
    import typer

    _TyperApp = typer.Typer
    _ClickCommand = Any
else:
    _TyperApp = Any
    _ClickCommand = Any


__all__ = ["TyperAdapter", "attach_typer", "get_typer_command"]


def _require_typer() -> Any:
    """Import Typer on demand and provide an actionable optional-dependency error."""

    try:
        import typer
    except ImportError as exc:  # pragma: no cover - exercised without the extra
        raise RuntimeError(
            "The Typer adapter requires the optional 'typer' dependency. Install it with 'pip install base-cli[typer]'."
        ) from exc
    return typer


def get_typer_command(typer_app: _TyperApp) -> _ClickCommand:
    """Materialize Typer's native Click command tree.

    The returned object is the command generated by Typer itself; it is not a
    copy and is suitable for passing to :func:`base_cli.attach` or
    :meth:`base_cli.App.attach`.
    """

    typer = _require_typer()
    if not isinstance(typer_app, typer.Typer):
        raise TypeError("get_typer_command() requires a typer.Typer instance.")

    try:
        from typer.main import get_command
    except ImportError as exc:  # pragma: no cover - defensive for broken Typer installs
        raise RuntimeError(
            "The installed Typer version does not expose its command adapter. "
            "Install a supported version with 'pip install base-cli[typer]'."
        ) from exc

    command = get_command(typer_app)
    dialect = dialect_for_typer(typer)
    if not isinstance(command, dialect.Command):
        raise TypeError(
            "Typer did not produce a Click command; upgrade to a supported "
            "Typer release (currently 0.12 through 0.27.x)."
        )
    return mark_command_dialect(command, dialect)


def _name_command_for_lifecycle(
    command: _ClickCommand,
    *,
    app: App | None,
    requested_name: str | None,
) -> None:
    """Give Typer's unnamed multi-command root a base-cli canonical name."""

    command_name = getattr(command, "name", None)
    target_name = requested_name or (app.name if app is not None else None)
    if command_name:
        if target_name and command_name != target_name:
            # Explicitly selecting a lifecycle name is useful for Typer's
            # single-command form, whose generated root name is the callback
            # name.  Mutating only this generated Click object preserves all
            # Typer-owned callbacks and parameters.
            command.name = target_name
        return
    if not target_name:
        raise RuntimeError(
            "Typer produced an unnamed command group. Pass name='your-cli' or construct a named base_cli.App."
        )
    command.name = target_name


class TyperAdapter:
    """Attach one Typer application to a base-cli lifecycle.

    The adapter caches Typer's generated command so callers can safely use the
    returned command for production entry points and tests without creating a
    second command tree.
    """

    def __init__(self, typer_app: _TyperApp) -> None:
        _require_typer()
        self.typer_app = typer_app
        self.command = get_typer_command(typer_app)

    def attach(
        self,
        *,
        app: App | None = None,
        context_factory: Callable[[Context[Any, Any, Any]], Any] | None = None,
        service_factory: Callable[[Context[Any, Any, Any]], Any] | None = None,
        sensitive_parameters: Iterable[str] = (),
        name: str | None = None,
        **app_kwargs: Any,
    ) -> _ClickCommand:
        """Attach the cached Typer command and return that same Click object."""

        if app is not None and app_kwargs:
            unexpected = ", ".join(sorted(app_kwargs))
            raise TypeError(f"App constructor arguments cannot be used with app= ({unexpected}).")
        if name is not None:
            if "name" in app_kwargs:
                raise TypeError("Specify the Typer lifecycle name only once.")
            if app is None:
                app_kwargs["name"] = name
        _name_command_for_lifecycle(
            self.command,
            app=app,
            requested_name=name or app_kwargs.get("name"),
        )
        return attach(
            self.command,
            app=app,
            context_factory=context_factory,
            service_factory=service_factory,
            sensitive_parameters=sensitive_parameters,
            **app_kwargs,
        )


def attach_typer(
    typer_app: _TyperApp,
    *,
    app: App | None = None,
    context_factory: Callable[[Context[Any, Any, Any]], Any] | None = None,
    service_factory: Callable[[Context[Any, Any, Any]], Any] | None = None,
    sensitive_parameters: Iterable[str] = (),
    name: str | None = None,
    **app_kwargs: Any,
) -> _ClickCommand:
    """Attach a Typer application and return its native Click command.

    ``app_kwargs`` are forwarded to the generic :class:`base_cli.App` when no
    explicit ``app`` is supplied.  In particular, the generated Typer command
    name is used as the canonical lifecycle name by default.
    """

    return TyperAdapter(typer_app).attach(
        app=app,
        context_factory=context_factory,
        service_factory=service_factory,
        sensitive_parameters=sensitive_parameters,
        name=name,
        **app_kwargs,
    )
